services:
  postgres:
    image: pgvector/pgvector:pg17
    container_name: wanderwise-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pswd
      POSTGRES_DB: wanderwise
    ports:
      - "5432:5432"
    volumes:
      - pgvector_data:/var/lib/postgresql/data

volumes:
  pgvector_data: