services:
  postgres:
    image: pgvector/pgvector:pg17
    container_name: wanderwise-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pswd
      POSTGRES_DB: wanderwise
    ports:
      - "5432:5432"
    volumes:
      - pgvector_data:/var/lib/postgresql/data
  
  grafana:
    image: grafana/grafana:latest
    container_name: wanderwise-grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    restart: unless-stopped

volumes:
  pgvector_data:
  grafana_data: